<h1>Agregar Tarea</h1>

<form action="<?php echo APP_URL."tareas/agregar"; ?>" method="POST">
	
	<label for="nombre">Nombre</label>
	<input type="text" name="nombre">
	<br>
	<br>

	<label for="descripcion">Descripción</label>
	<textarea name="descripcion"></textarea>
	<br>
	<br>

	<label for="fecha">Fecha</label>
	<input type="date" name="fecha" value="<?php echo date("y-m-d"); ?>">
	<br>
	<br>

	<label for="prioridad">Prioridad</label>
	<input type="range" name="prioridad" min="0" max="10">
	<br>
	<br>

	<label for="categoria">Categoría</label>
	<select name="categoria_id">

		<?php 

			foreach ($this->categorias as $categoria) { ?>
				
				<option value="<?php echo $categorias["id"]; ?>">
					<?php echo $categoria["nombre"]; ?></option>

		<?php } ?>

	</select>
	<br>
	<br>

	<input type="submit">

</form>